### PR TITLE
Fixed import and added maven

### PR DESCRIPTION
**Pull request by justADeni**
Was having issues with importing this project but all it needed was a small fix

### CODE REVIEW

**Review by Boy0000 — APPROVED** [review]
the # in the repository url is strictly not needed but doesnt break it either
but yeah ur right it is -api

**Comment by 0ffz** [comment]
I'll check it out once I'm home, it might be publishing the full jar including generated classes for the non API version, in which case you're correct about using API only.

**Comment by justADeni** [comment]
Hi, I hope you don't mind, I really like this project and made a logo for it. It is okay?

**Comment by 0ffz** [comment]
Looking over it again, you actually do want the main one and not just api since you need the generated classes to actually interact with the packets. What issues were you having? I'll be merging develop right now for 1.20 support, maybe you can give that a go?

Also the logo's cool, you could put it in the `.idea/icon.svg` to make it show up for developers in intellij too, though it needs to be an svg for that (you can just convert the png to svg for it even though it's a bit inefficient.)

**Comment by justADeni** [comment]
Thank you. I tried the main one, which I can 'see' is there:
scr1

But then it fails to import the main one:
scr2

Do you have any such issues or is something broken on my end?

Also regarding the logo, I realized I accidentally drew a taco instead of burrito so imma remake that. I'll make a new one later with only the correct logo?

**Comment by 0ffz** [comment]
You could try putting our repo before papermc's and seeing if it helps, I get similar issues with maven sometimes, probably just caches something wrong, idk for certain :(

Interesting that it looks for `:jar:` specifically though. Not sure if maven just formats it differently but I think `com.mineinabyss:protocolburrito:jar:0.6.3` is a valid dependency in gradle, though it'd be searching in the wrong place in this case.

**Comment by justADeni** [comment]
Hi, sorry for bumping this again after long time. I have resorted to importing ProtocolBurrito as a .jar to my project, which seems to work fine. However with version 0.7.0 I ran into a problem, that it no longer works on 1.19.4 or below: 
`[23:28:22 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'protocolburrito-plugin-0.7.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.20
        at org.bukkit.craftbukkit.v1_19_R3.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:380) ~[paper-1.19.4.jar:git-Paper-501]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:119) ~[paper-1.19.4.jar:git-Paper-501]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.19.4.jar:git-Paper-501]
        at io.papermc.paper.plugin.entrypoint.strategy.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:150) ~[paper-1.19.4.jar:git-Paper-501]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:35) ~[paper-1.19.4.jar:git-Paper-501]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.19.4.jar:git-Paper-501]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:423) ~[paper-1.19.4.jar:git-Paper-501]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.19.4.jar:git-Paper-501]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-501]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-501]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]`

Is it really only for 1.20 and thus working correctly? Because otherwise if you removed specifying API version i think it'd work. Again, sorry for bothering you guys

**Comment by 0ffz** [comment]
I think it should mostly work since it's just referencing indices and using protocol lib, but might lead to inconsistencies. I think the best solution would be to build against multiple versions and do a warning for unsupported ones. I can have a look but in the meantime you can just edit the plugin yml in the jar and hope for the best.

**Pull request closed without merging**
